version: '3'

services:
  php:
    build: .
    volumes:
      - ./src:/var/www/html/src
      - ./config:/var/www/html/config
      - ./public:/var/www/html/public
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      APP_ENV: dev
      APP_SECRET: your_secret_here
      DATABASE_URL: "postgresql://user:password@database:5432/weather_api?serverVersion=13&charset=utf8"
      WEATHER_API_KEY: 4d114cd7ef0de08aa86928da3254c502

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: weather_api
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d weather_api"]
      interval: 5s
      timeout: 5s
      retries: 5